export const WHATSAPP_INBOUND_MESSAGE_REPOSITORY = Symbol('WHATSAPP_INBOUND_MESSAGE_REPOSITORY');
export const WHATSAPP_OUTBOUND_MESSAGE_REPOSITORY = Symbol('WHATSAPP_OUTBOUND_MESSAGE_REPOSITORY');
export const WHATSAPP_MESSAGING_PROVIDER = Symbol('WHATSAPP_MESSAGING_PROVIDER');
export const WHATSAPP_CREDENTIAL_STORE = Symbol('WHATSAPP_CREDENTIAL_STORE');
