export const WHATSAPP_ONBOARDING_TRANSACTION_REPOSITORY = Symbol('WHATSAPP_ONBOARDING_TRANSACTION_REPOSITORY');
export const META_WHATSAPP_CONFIG = Symbol('META_WHATSAPP_CONFIG');
export const WHATSAPP_CONNECTION_PROVIDER = Symbol('WHATSAPP_CONNECTION_PROVIDER');
